-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.todos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    userid uuid,
    name text COLLATE pg_catalog."default",
    CONSTRAINT todos_pkey PRIMARY KEY (id),
    CONSTRAINT todos_userid_fkey FOREIGN KEY (userid)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.todos
    OWNER to postgres;

ALTER TABLE IF EXISTS public.todos
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.todos TO anon;

GRANT ALL ON TABLE public.todos TO authenticated;

GRANT ALL ON TABLE public.todos TO postgres;

GRANT ALL ON TABLE public.todos TO service_role;
CREATE POLICY "CRUD based on userid"
    ON public.todos
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.uid() = userid))
    WITH CHECK ((auth.uid() = userid));
